name: Release Docker Image

on:
  push:
    tags:
      - "*" # Run on any tag; steps below filter to semver (e.g., 1.0.0)

jobs:
  docker:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Extract semver tag
        id: semver
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "version=$TAG" >> "$GITHUB_OUTPUT"
            echo "Tag recognized as semver: $TAG"
          else
            echo "Tag '$TAG' is not semver (e.g., 1.0.0)."
          fi

      - name: Set image name
        id: img
        if: ${{ steps.semver.outputs.version != '' }}
        shell: bash
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          echo "image=${DOCKERHUB_USERNAME}/${REPO_NAME}" >> "$GITHUB_OUTPUT"
          echo "Image will be: ${DOCKERHUB_USERNAME}/${REPO_NAME}"

      - name: Set up QEMU
        if: ${{ steps.semver.outputs.version != '' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ steps.semver.outputs.version != '' }}
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: ${{ steps.semver.outputs.version != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.semver.outputs.version != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.img.outputs.image }}:${{ steps.semver.outputs.version }}
            ${{ steps.img.outputs.image }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.semver.outputs.version }}